name = "base-api-cloudflare"
main = "src/index.ts"
compatibility_date = "2024-01-01"

[vars]
LOG_LEVEL = "info"
API_VERSION = "1.1.0"

[[d1_databases]]
binding = "DB"
database_name = "sybilla-db"
database_id = "5dfeef5a-9a22-4735-a35c-8dcb21a23c33"

[dev]
port = 3000